# Generated by Django 2.2.7 on 2019-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=60)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('weekday', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('prof', models.CharField(max_length=60)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('day', models.DateField()),
            ],
        ),
    ]
