# Generated by Django 2.2.7 on 2019-11-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_freetime_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetime',
            name='weekday',
            field=models.IntegerField(),
        ),
    ]
